services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-native-app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: kampus_db
      DB_USER: kampus_user
      DB_PASS: kampus_pass
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.4
    container_name: php-native-db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: kampus_db
      MYSQL_USER: kampus_user
      MYSQL_PASSWORD: kampus_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot_pass"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
